---
rootFolderProject:  .
toolboxFolder:  Toolbox/

pagesImagesFolder:  Pages/
pagesResolution: 300

hocrFolder:   Layout/hocr-charboxes/
ocrLanguage:  fra
hocrMarginPixel:  2

capHeight: 0

extractedGlyphImageFolder: Glyphs/auto-extracted/

sortedGlyphImageFolder: Glyphs/auto-extracted/
sortInSameFolder: 0

fontStyles:
  - italic
  - smallCaps

cssSelectors:
  i: italic
  em: italic
  .page_smallCaps: smallCaps

averageFolder: Glyphs/average/

levelsFolder: Glyphs/levels/
levelValues:
  - 15
  - 30
  - 60
  - 40
deltaValues:
  - 20
blurValues:
  - "0x8"

resizedFolder: Glyphs/resized/

pnmFolder: Glyphs/clean/

vectorsFolder: Glyphs/vectors/
nbSimple: 0
ifHTML: 0
validLevelValue: 30

svgFontSourceFile: Toolbox/font.svg
svgFontFile: Font/font.svg

fontSourceFile: Font/font.sfd
individualGlyphFolder: Font/individualGlyphs/

metricsFile: Font/metrics.json

cadratinSize: 1000

webViewerFolder: Toolbox/WebViewer/
webViewerPort: 8000
multToCadratin: 8
...
